import Provider from "@/context/provider";
import { Inter } from "next/font/google";
import { ReduxProvider } from "../libs/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <ReduxProvider>
          <body className={inter.className}>{children}</body>
        </ReduxProvider>
      </Provider>
    </html>
  );
}
